### ISSUE TITLE
Error in fill percentage calculation

### ISSUE THREAD

**Issue by daFreeMan** [jtsage/FS22_simpleInspector#17]
**Describe the bug**
Using the Kubota XTS446 Sprayer and Kubota XFT211 from the [Kubota Equipment Pack by Iconik](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=247044&title=fs2022), both with the "XL" capacity, I have a total of 2000 liters capacity (5000 for the tank, 15000 for the sprayer).

Simple Inspector correctly shows the 20000 liters capacity, but reports it at 190% full. Since it can't figure out what to do with a value > 100%, it also shows the fill level in white text.

**To Reproduce**
1. Purchase the two Kubota accessories and attach them to a tractor
2. Load them with a liquid of your choice.
   1. I'm using liquid fertilizer, but I would think the error would happen with any liquid. I haven't tested.
1. See error

**Expected behavior**
It should display 100% (colored green) when it's full

**Screenshots**
![image](https://user-images.githubusercontent.com/11889733/185183521-ed14ab20-2c7c-4aeb-91cc-ad611c62da29.png)

For reference, here are the 2 pieces of equipment in question:
![image](https://user-images.githubusercontent.com/11889733/185183644-f48e2782-6907-4a8c-a4cc-a8b0bd9159f4.png)
![image](https://user-images.githubusercontent.com/11889733/185183683-5fa51ab2-5ba7-4fd6-952a-098e8db82501.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 
    - SI: 1.0.1.8
    - FS: 1.6

**Additional context**
Note that I do _not_ have this issue when using the John Deere R732i PowrSpray that comes with the PrecisionFarming mod and the base-game HARDI 1200l tank. Therefore, this does seem to be particular to these two mod items.

**Comment by jtsage** [comment]
Aye, I suspect Iconik did something a little different - I've not used this set up yet, but I totally dig that pack, so I'll take a look at what I'm missing and push it in the next update.  I'll ping you again here when I have a chance to look at this.

**Comment by jtsage** [comment]
I'll keep playing with this, but I couldn't reproduce it on my end - same equipment purchased, fill level shows as 20k (100%).

**Comment by daFreeMan** [comment]
Hrm, pretty weird. I get it consistently at my end. As soon as I get a chance, I'll try with a couple of different tractors. Maybe it's related to the motive power...

**Comment by daFreeMan** [comment]
Here's a base-game Claas Axion 660:
![image](https://user-images.githubusercontent.com/11889733/189497422-d862cc35-69da-4136-898a-554eaddd31eb.png)

And here's a different JCB (by the same modder as the one in the original): 
![image](https://user-images.githubusercontent.com/11889733/189497435-18017d87-fab9-465a-912c-9fc2c4ebab44.png)

**Comment by daFreeMan** [comment]
Now it's _really_ gone nuts!

![image](https://user-images.githubusercontent.com/11889733/189500354-ff444831-3215-4f68-8ef3-1cf75a115ed1.png)

**Comment by jtsage** [comment]
So, what you are saying is I clearly did *not* fix it.  Gotcha.  I'm actually in the middle of a massive re-write of this whole thing, I will take a much closer look at this sometime soon.

Just for reference, are you using any other script mods that might mess with fill types or levels?  I do try and plan for any other mods that mess about in ways I didn't think of, always looking to expand the test list.

Thanks!

**Comment by daFreeMan** [comment]
I'm running, 1.0.1.8, so I guess not. :( 

Am I using other script mods? Yes. That will interfere with it, well, I haven't a clue. I've got a small collection of mods I'm using. I suppose I should test this out w/o them and see if I can find a conflict somewhere.

I'll report back.

**Comment by daFreeMan** [comment]
Ah ha!!
![image](https://user-images.githubusercontent.com/11889733/189713190-0f10ce7e-c786-4f1b-9583-9224a66b5966.png)
![image](https://user-images.githubusercontent.com/11889733/189713224-61f29c01-b147-43de-93b4-3a4b6dc50de2.png)

Yet...
![image](https://user-images.githubusercontent.com/11889733/189713331-26498bdf-084d-4ae8-8822-fb8d262c2a33.png)
![image](https://user-images.githubusercontent.com/11889733/189713348-08fda80a-786a-4879-9f94-869f1c8a1559.png)

It's not a mod conflict. Seems that it's confused by the trailer fill limit setting.

This is in a test game with only simpleInspector and the Kubota pack installed, but I'd presume it's the same with all the other mods, too.

**Comment by jtsage** [comment]
Aww...  I had kind of hoped it wasn't that bit, there is some, er...  "interesting" math there - but, this is awesome, it gives me a great way to test, and where to fix it.  Thanks so much for keeping at it!  (and of course, that option is off by default, which is why my quick testing never brought it up before.)

**Comment by jtsage** [comment]
Anyway, the root of the problem is I am nearly certain (without being at the right computer to check), that I only grab the weight limit from one of the implements, not ## implements with that type of fill, so, in a sense, it having 190% of what it could hold is correct, just not a useful statistic :)

**Comment by jtsage** [comment]
So, it turns out it wasn't *totally* my fault - just mostly.  The kubota pack makes use of `updateMass="false"` in the fillUnit's for the XL versions, so they can far exceed the amount they "should" be able to hold with that setting on.  So, I changed that section of the code to also ignore the additional mass when that setting is toggled - that should fix the percentage calculation.

I am in the middle of a partial re-write of the whole thing, so this fix isn't in the main branch yet - if you want to test, https://github.com/jtsage/FS22_simpleInspector/raw/dev_modules/FS22_SimpleInspector.zip will get you the zip - just keep in mind the version number will be the same, but it won't work with anybody who doesn't have the same download.

I hope to have the changes in there mostly sorted by this weekend so I can send them off to giants.

**Comment by daFreeMan** [comment]
Sorry to hear it was in an "interesting" bit of code. :) those are always the least amount of fun. The rewrite should, I'm sure get rid of some tech debt and make it easier to maintain in the future.

Glad you figured out what's going wrong on your end and that it wasn't all your fault. 

I have the patch version downloaded and will give it a try next time I'm in the game. I'll keep an eye out for the next release version, and if you want someone to do some beta testing, feel free to give me a shout. I'm always good at finding the issues in other people's code. If only I were half decent at finding them in my own before the others do... 😆

**Comment by daFreeMan** [comment]
Winner, winner, chicken dinner!
![image](https://user-images.githubusercontent.com/11889733/190007847-82546547-d94f-4e6f-a2af-93c6c2fcaa72.png)
![image](https://user-images.githubusercontent.com/11889733/190007857-39227fad-64e2-4f4d-8ec4-ff0a91505e3a.png)

I also love the update color coding the fuel fill level!

I'd say you can close this one out unless you've got something else in relation to tweak.

**Comment by jtsage** [comment]
great. That version is probably just about ready - I just need to spend some time playing with it on and make sure I didn't mess something up.  Probably a quick MP test too and it should be ready to go off for testing.

**Comment by jtsage** [comment]
correction pushed to modhub, should be out in a few days.  Fwiw, the fuel level thing wasn't entirely intentional, but I like it too.  Also, if you watch the colors, they now "stick" on the "good" side - i.e. that Liquid fertilizer will stay bright green for a bit and then ramp down quicker, it's not a totally linear progression anymore.
