### ISSUE TITLE
Driver names (multiplayer)

### ISSUE THREAD

**Issue by Ginks-dk** [jtsage/FS22_simpleInspector#6]
Hello

Don't know if it's possible in FS22.!
But it would need great to have the player names displayed.

Thx for a great mod

Chr

**Comment by jtsage** [comment]
Sure.  it's only active on multiplayer, because seeing my shortened, wrong name on single player where I didn't have to care bothers me.  Also configurable via the xml file.  This will be 1.0.0.6, although it's already in the zip file that'll hit just below - going to hold 1.0.0.6 until the end of the weekend so I only pull/resubmit once this weekend on the modhub.

**Comment by Ginks-dk** [comment]
Thx your for the quick response.
Looking forward to 1.0.0.6

**Comment by jtsage** [comment]
v1.0.1.0 published, this contains this fix too.
