### ISSUE TITLE
Show Vehicles in Farmcolors 

### ISSUE THREAD

**Issue by HurrycaneBE** [jtsage/FS22_simpleInspector#9]
Hey ,
the mod runs wonderfull.... but
is it possible to show the vehicles in Farm Colors and maybe Sort of it ?
This would be really nice !

Thank you 4 ur work !
P.S.: You dont need to use a rented dedicated server ... Contact me we invite you to our Testmachine ;)

**Comment by jtsage** [comment]
So, I'm gonna take this in two parts:

1.) sorting - I haven't done this, because right now, it should be in tab order. And if you use a mod like vehicleexplorer, you can change that tab order.  If folks really want it, sorting alphabetical isn't all the difficult, I could make it a configuration option.

2.) Farm color - yeah, I could add this - for the vehicle name though?  Are you using the option that always shows everything? Because if I do this (as an option), you'd lose all the special colors for vehicles turned on / AI driving, etc.  Does color coding the player name by farm make more sense?  And as I don't really MP - should that player name be their color, or should it reflect who the vehicle belongs to (is that even possible, to drive other peoples stuff?)

**Comment by BonzTM** [comment]
I like this idea, but how difficult is it to be able to just sort with a label per farm?  And have the ability to turn on/off the difference between "Your own" and "Other farms"?

The current version of vehicleinspector has this ability bound to `K` by default for reference

**Comment by jtsage** [comment]
can you shoot me a screenshot of what your after - I'm still not following exactly.

thanks.

**Comment by BonzTM** [comment]
If you want me to create a new issue since it's not exactly the same as OP's, I will.

This is VehicleInspector showing just my own equipment (on my farm, that I own or lease):
![image](https://user-images.githubusercontent.com/514931/155824422-472b9d6e-b6ad-4b34-8f69-cafbddbee8ab.png)

This is VehicleInspector after pressing `K` to toggle the view the vehicles owned by all other farms:
![image](https://user-images.githubusercontent.com/514931/155824453-1d12cb20-58b5-4517-b138-1b7dfa57e2b7.png)

I'd love to keep all the configuration options minimal like they currently are, but just be able to toggle my own equipment vs. other farm's equipment.

**Comment by jtsage** [comment]
nah, same issue is fine.  I see what you mean now. let me chase down how to do this, and throw it in when I have a chance (probably tomorrow sometime - I'm going to have to backport some of the changed display code from productions/animal inspector to handle the "extra" lines).  I might add a few empty keybinds for this sort of stuff too, which is how things like AutoDrive handle a bunch of the less commonly used options, so they don't clutter up the limited space by default.

**Comment by BonzTM** [comment]
@jtsage wonderful!

I hope this satisfies @HurrycaneBE, but it definitely satisfies what I was looking for :)

**Comment by HurrycaneBE** [comment]
hello , sry 4 my late answer.
for me , is the actual solution okay :)
